apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: mighty-tyrannosaurus-go
  janus-idp.io/tekton: mighty-tyrannosaurus-go
  backstage.io/kubernetes-id: mighty-tyrannosaurus-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: mighty-tyrannosaurus-go
resources:
- deployment.yaml
- route.yaml
- service.yaml
